param(
  [string]$SourcePath,
  [switch]$Deploy,
  [switch]$NoClean
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Resolve-WeakAurasRoot {
  param([string]$HintPath)

  if (-not [string]::IsNullOrWhiteSpace($HintPath)) {
    $resolved = Resolve-Path -LiteralPath $HintPath -ErrorAction Stop
    return (Get-Item -LiteralPath $resolved).FullName
  }

  $candidates = @(
    "F:\World of Warcraft\_retail_\Interface\AddOns\WeakAuras",
    "F:\World of Warcraft\_ptr_\Interface\AddOns\WeakAuras",
    "F:\World of Warcraft\_xptr_\Interface\AddOns\WeakAuras"
  )
  foreach ($path in $candidates) {
    if (Test-Path -LiteralPath $path) {
      return $path
    }
  }
  throw "WeakAuras folder not found. Pass -SourcePath with the WeakAuras addon root path."
}

function Sanitize-TokenPart {
  param([string]$Text)
  $x = ($Text -replace '[^a-zA-Z0-9]', '_').ToLowerInvariant().Trim('_')
  if ([string]::IsNullOrWhiteSpace($x)) {
    return "sound"
  }
  return $x
}

$repoRoot = $PSScriptRoot
$waRoot = Resolve-WeakAurasRoot -HintPath $SourcePath
$waSoundRoot = Join-Path $waRoot "Media\Sounds"
if (-not (Test-Path -LiteralPath $waSoundRoot)) {
  throw "WeakAuras sounds folder not found: $waSoundRoot"
}

$destRoot = Join-Path $repoRoot "AuraLite\Media\Sounds\WeakAuras"
if ((-not $NoClean) -and (Test-Path -LiteralPath $destRoot)) {
  Remove-Item -LiteralPath $destRoot -Recurse -Force
}
if (-not (Test-Path -LiteralPath $destRoot)) {
  New-Item -ItemType Directory -Path $destRoot -Force | Out-Null
}

$audioFiles = Get-ChildItem -LiteralPath $waSoundRoot -File -ErrorAction Stop |
  Where-Object { $_.Extension.ToLowerInvariant() -in @(".ogg", ".mp3", ".wav") } |
  Sort-Object Name

if ($audioFiles.Count -eq 0) {
  throw "No audio files found in $waSoundRoot"
}

$entries = @()
$usedTokens = @{}
$usedNames = @{}

foreach ($file in $audioFiles) {
  $baseName = [IO.Path]::GetFileNameWithoutExtension($file.Name)
  $ext = $file.Extension.ToLowerInvariant()

  $safeBase = ($baseName -replace '[^a-zA-Z0-9_\-]', '_').Trim('_')
  if ([string]::IsNullOrWhiteSpace($safeBase)) {
    $safeBase = "wa_sound"
  }
  $destName = "$safeBase$ext"
  $n = 2
  while ($usedNames.ContainsKey($destName)) {
    $destName = "${safeBase}_$n$ext"
    $n++
  }
  $usedNames[$destName] = $true

  Copy-Item -LiteralPath $file.FullName -Destination (Join-Path $destRoot $destName) -Force

  $tokenBase = Sanitize-TokenPart -Text $baseName
  $token = "wa_$tokenBase"
  $m = 2
  while ($usedTokens.ContainsKey($token)) {
    $token = "wa_${tokenBase}_$m"
    $m++
  }
  $usedTokens[$token] = $true

  $entries += [PSCustomObject]@{
    Token = $token
    Label = "WA: $baseName"
    File = "Interface\\AddOns\\AuraLite\\Media\\Sounds\\WeakAuras\\$destName"
    Name = $destName
  }
}

$catalogPath = Join-Path $repoRoot "AuraLite\WeakAurasSoundCatalog.lua"
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("local _, ns = ...")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- Generated by import-wa-sounds.ps1. Do not edit by hand.")
[void]$sb.AppendLine("ns.WeakAurasSoundCatalog = {")
foreach ($e in ($entries | Sort-Object Token)) {
  $token = $e.Token.Replace("\", "\\").Replace('"', '\"')
  $label = $e.Label.Replace("\", "\\").Replace('"', '\"')
  $path = $e.File.Replace("\", "\\").Replace('"', '\"')
  [void]$sb.AppendLine(("  [""{0}""] = {{ label = ""{1}"", file = ""{2}"" }}," -f $token, $label, $path))
}
[void]$sb.AppendLine("}")
Set-Content -LiteralPath $catalogPath -Value $sb.ToString() -Encoding ASCII

$totalBytes = ($audioFiles | Measure-Object Length -Sum).Sum
$totalMB = [math]::Round(($totalBytes / 1MB), 2)
Write-Host ("Imported {0} WeakAuras sounds ({1} MB)." -f $entries.Count, $totalMB) -ForegroundColor Green
Write-Host ("Catalog updated: {0}" -f $catalogPath) -ForegroundColor Cyan
Write-Host ("Source: {0}" -f $waSoundRoot) -ForegroundColor DarkCyan
Write-Host ("Destination: {0}" -f $destRoot) -ForegroundColor DarkCyan

if ($Deploy) {
  $deployScript = Join-Path $repoRoot "deploy.ps1"
  if (-not (Test-Path -LiteralPath $deployScript)) {
    throw "deploy.ps1 not found at $deployScript"
  }
  powershell -NoProfile -ExecutionPolicy Bypass -File $deployScript
}
