local _, ns = ...

ns.Localization = ns.Localization or {}
local L = ns.Localization

L.tables = L.tables or {
  enUS = {
    ui_title = "AuraLite - Aura Editor",
    quick_actions = "Quick Actions",
    aura_list = "Aura List",
    aura_details = "Aura Details",
    tab_general = "Aura",
    tab_display = "Display",
    tab_sounds = "Actions",
    tab_rules = "Trigger",
    btn_lock = "Lock Drag",
    btn_unlock = "Unlock Drag",
    btn_edit_on = "Edit: ON",
    btn_edit_off = "Edit: OFF",
	    btn_refresh = "Refresh",
	    btn_localization = "Localization / UI",
	    btn_rules = "Rules",
	    btn_global_options = "Global Settings",
    lbl_compact = "Compact",
    lbl_show_source = "Show Source",
	    lbl_enable_sounds = "Enable Sounds",
	    lbl_debug_chat = "Debug Chat",
	    lbl_rules_only = "Rules Only",
    lbl_channel = "Channel",
    lbl_low_time = "Low-time (s)",
    lbl_workspace = "Workspace",
    ws_auras = "Auras",
    ws_editor = "Editor",
    ws_split = "Split",
    lbl_guided_mode = "Guided UI",
    hint_library = "Step 1: Select an aura from the list or create a new one.",
    hint_editor = "Step 2: Configure trigger, visuals and sounds for the selected aura.",
    hint_split = "Pro view: list and editor side by side.",
    hint_guided = "Guided mode hides advanced fields for simpler setup.",
	    hint_advanced = "Advanced mode shows all fields and fine-tuning options.",
	    global_title = "Global Settings",
	    global_hint = "These settings apply to the active profile and affect all tracked auras.",
	    editor_health_ready = "Aura is ready. You can test and save.",
	    editor_health_spell_missing = "Pick a spell (ID or name) to complete this aura.",
	    editor_health_rule_missing = "Rules-only mode: add at least one trigger rule for this aura.",
	    editor_health_mode_edit = "Mode: Edit",
	    editor_health_mode_create = "Mode: Create",
    lbl_filter = "Filter",
    btn_clear = "Clear",
    btn_new_aura = "New Aura",
    btn_duplicate = "Duplicate",
    btn_remove = "Remove",
    editor_none = "No aura selected",
    editor_new = "New Aura",
    editor_edit = "Edit: %s",
    lbl_spell = "SpellID / Name",
    lbl_aura_name = "Aura Name (optional)",
    lbl_unit = "Unit",
    lbl_group = "Group",
    lbl_group_custom = "New Group ID (optional)",
    lbl_only_mine = "Only mine",
    lbl_low_alert = "Low-time alert",
    lbl_low_time_aura = "Low-time (aura, s)",
	    lbl_icon = "Icon",
	    opt_spell_icon = "Spell Icon",
	    opt_custom_path = "Custom Path",
	    lbl_cd_visual = "CD Visual",
	    opt_cd_icon = "Icon",
	    opt_cd_bar = "Bar",
      opt_cd_icon_bar = "Icon + Bar",
      opt_default_texture = "Default",
	    lbl_custom_texture = "Custom texture path",
    help_custom_texture = "Example: Interface\\AddOns\\AuraLite\\Media\\Custom\\myfile",
      lbl_bar_texture = "Bar texture path (optional)",
      help_bar_texture = "Example: Interface\\TargetingFrame\\UI-StatusBar",
	    lbl_custom_text = "Custom text (optional)",
	    help_custom_text = "Tokens: {name} {spell} {stacks} {remaining} {duration} {source} {unit}",
	    lbl_resource_condition = "Primary resource condition",
	    lbl_resource_range = "Resource % Min/Max",
    lbl_resource_current_fmt = "%s: %d%%",
    lbl_resource_current_na = "%s: N/A",
	    lbl_timer_anchor = "Timer Anchor",
    lbl_timer_offset = "Timer Offset X/Y",
    lbl_text_anchor = "Text Anchor",
    lbl_text_offset = "Text Offset X/Y",
    lbl_sound_title = "Sounds by aura state",
    lbl_sound_gain = "Gain",
    lbl_sound_low = "Low Time",
    lbl_sound_expire = "Expire",
    btn_test = "Test",
    btn_save = "Save Aura",
    btn_reset = "Reset Form",
    btn_open_options = "Open Interface Options",
    loc_title = "Localization & Appearance",
    loc_language = "Language",
    loc_theme = "Theme",
    loc_theme_modern = "Modern",
    loc_theme_classic = "Classic",
    loc_texture = "Custom UI texture (optional)",
    loc_texture_help = "Path or Media/Custom name (import-texture.ps1).",
    loc_apply = "Apply",
    loc_close = "Close",
    lang_en = "English (Default)",
    lang_it = "Italiano",
    msg_no_audio_path = "Insert an audio path before test.",
    msg_category_unavailable = "Options category is not available on this client.",
    msg_spell_missing = "Insert SpellID or spell name.",
    msg_add_ok = "Aura added.",
    msg_add_fail = "Aura creation failed.",
    msg_select_missing = "No aura selected.",
    msg_update_ok = "Aura updated.",
    msg_update_fail = "Aura save failed.",
    msg_remove_pick = "Select an aura to remove.",
    msg_remove_ok = "Aura removed.",
    msg_duplicate_pick = "Select an aura to duplicate.",
    msg_duplicate_missing = "Selected aura not found.",
    msg_duplicate_fail = "Unable to duplicate aura.",
    msg_duplicate_ok = "Aura duplicated.",
    msg_audio_path_missing = "Missing audio path for %s.",
    msg_language_applied = "Language applied: %s",
    msg_style_applied = "UI style applied: %s",
    rules_title = "Trigger Builder",
    rules_list = "Configured Rules",
    rules_type = "Rule Type",
	    rule_type_if = "Cast -> Show Aura",
	    rule_type_consume = "Cast -> Consume Aura",
	    rule_id = "Rule ID",
	    rule_cast_spell = "Cast SpellIDs (CSV)",
	    rule_talent_spell = "Talent SpellIDs (optional, CSV)",
    rule_condition_mode = "Condition Logic",
    rule_condition_and = "AND (all)",
    rule_condition_or = "OR (any)",
	    rule_condition_aura = "Required Aura SpellIDs (optional, CSV)",
	    rule_condition_combat = "In combat only",
	    rule_aura_spell = "Aura SpellID",
		    rule_duration = "Duration (sec)",
		    rule_csv_hint = "CSV example: 6343,23922",
	    rule_narrative_when = "WHEN Cast",
	    rule_narrative_if = "IF",
	    rule_narrative_then = "THEN",
	    rule_narrative_show = "Show aura for",
	    rule_narrative_consume = "Consume aura",
    rules_save = "Save Rule",
    rules_remove = "Remove Rule",
    rules_clear = "Clear All",
    rules_close = "Close",
    rules_new = "New Rule",
    rules_tab_trigger = "Trigger",
    rules_tab_conditions = "Conditions",
    rules_tab_actions = "Actions",
    msg_rule_saved = "Rule saved.",
    msg_rule_removed = "Rule removed (%d).",
    msg_rule_clear = "All rules cleared.",
    msg_rule_pick = "Select a rule first.",
    msg_rule_invalid = "Invalid rule fields.",
	    tooltip_aura = "Aura: ",
	    tooltip_source = "Source: ",
	    row_status_ok = "Ready",
	    row_status_warn = "Needs setup",
	    row_warn_missing_rule = "No trigger rule configured (rules-only mode).",
	    row_warn_missing_texture = "Custom icon mode selected but texture path is empty.",
	    row_warn_missing_group = "Assigned group is missing or invalid.",
	  },
  itIT = {
    ui_title = "AuraLite - Editor Aura",
    quick_actions = "Azioni Rapide",
    aura_list = "Lista Aura",
    aura_details = "Dettagli Aura",
    tab_general = "Aura",
    tab_display = "Display",
    tab_sounds = "Azioni",
    tab_rules = "Trigger",
    btn_lock = "Blocca Drag",
    btn_unlock = "Sblocca Drag",
    btn_edit_on = "Edit: ON",
    btn_edit_off = "Edit: OFF",
	    btn_refresh = "Aggiorna",
	    btn_localization = "Localizzazione / UI",
	    btn_rules = "Regole",
	    btn_global_options = "Impostazioni Globali",
    lbl_compact = "Compatto",
    lbl_show_source = "Mostra Sorgente",
	    lbl_enable_sounds = "Abilita Suoni",
	    lbl_debug_chat = "Debug Chat",
	    lbl_rules_only = "Solo Regole",
    lbl_channel = "Canale",
    lbl_low_time = "Low-time (s)",
    lbl_workspace = "Workspace",
    ws_auras = "Aura",
    ws_editor = "Editor",
    ws_split = "Split",
    lbl_guided_mode = "UI Guidata",
    hint_library = "Step 1: seleziona un'aura dalla lista o creane una nuova.",
    hint_editor = "Step 2: configura trigger, visual e suoni dell'aura selezionata.",
    hint_split = "Vista Pro: lista ed editor affiancati.",
    hint_guided = "Modalita guidata: nasconde i campi avanzati.",
	    hint_advanced = "Modalita avanzata: mostra tutti i campi e il fine tuning.",
	    global_title = "Impostazioni Globali",
	    global_hint = "Queste impostazioni si applicano al profilo attivo e a tutte le aura tracciate.",
	    editor_health_ready = "Aura pronta. Puoi testare e salvare.",
	    editor_health_spell_missing = "Seleziona una spell (ID o nome) per completare l'aura.",
	    editor_health_rule_missing = "Modalita solo regole: aggiungi almeno una regola trigger per questa aura.",
	    editor_health_mode_edit = "Modalita: Modifica",
	    editor_health_mode_create = "Modalita: Creazione",
    lbl_filter = "Filtro",
    btn_clear = "Pulisci",
    btn_new_aura = "Nuova Aura",
    btn_duplicate = "Duplica",
    btn_remove = "Rimuovi",
    editor_none = "Nessuna aura selezionata",
    editor_new = "Nuova Aura",
    editor_edit = "Modifica: %s",
    lbl_spell = "SpellID / Nome",
    lbl_aura_name = "Nome Aura (opzionale)",
    lbl_unit = "Unita",
    lbl_group = "Gruppo",
    lbl_group_custom = "Nuovo Group ID (opzionale)",
    lbl_only_mine = "Solo mie",
    lbl_low_alert = "Avviso low-time",
    lbl_low_time_aura = "Low-time (aura, s)",
	    lbl_icon = "Icona",
	    opt_spell_icon = "Icona Spell",
	    opt_custom_path = "Path Custom",
	    lbl_cd_visual = "Visuale CD",
	    opt_cd_icon = "Icona",
	    opt_cd_bar = "Barra",
      opt_cd_icon_bar = "Icona + Barra",
      opt_default_texture = "Default",
	    lbl_custom_texture = "Path texture custom",
    help_custom_texture = "Esempio: Interface\\AddOns\\AuraLite\\Media\\Custom\\miofile",
      lbl_bar_texture = "Path texture barra (opzionale)",
      help_bar_texture = "Esempio: Interface\\TargetingFrame\\UI-StatusBar",
	    lbl_custom_text = "Testo custom (opzionale)",
	    help_custom_text = "Token: {name} {spell} {stacks} {remaining} {duration} {source} {unit}",
	    lbl_resource_condition = "Condizione risorsa primaria",
	    lbl_resource_range = "Risorsa % Min/Max",
    lbl_resource_current_fmt = "%s: %d%%",
    lbl_resource_current_na = "%s: N/D",
	    lbl_timer_anchor = "Anchor Timer",
    lbl_timer_offset = "Offset Timer X/Y",
    lbl_text_anchor = "Anchor Testo",
    lbl_text_offset = "Offset Testo X/Y",
    lbl_sound_title = "Suoni per stato aura",
    lbl_sound_gain = "Gain",
    lbl_sound_low = "Low Time",
    lbl_sound_expire = "Expire",
    btn_test = "Test",
    btn_save = "Salva Aura",
    btn_reset = "Reset Form",
    btn_open_options = "Apri Opzioni Interfaccia",
    loc_title = "Localizzazione e Aspetto",
    loc_language = "Lingua",
    loc_theme = "Tema",
    loc_theme_modern = "Moderno",
    loc_theme_classic = "Classico",
    loc_texture = "Texture UI custom (opzionale)",
    loc_texture_help = "Path o nome in Media/Custom (import-texture.ps1).",
    loc_apply = "Applica",
    loc_close = "Chiudi",
    lang_en = "English (Default)",
    lang_it = "Italiano",
    msg_no_audio_path = "Inserisci un percorso audio per il test.",
    msg_category_unavailable = "Categoria Opzioni non disponibile su questo client.",
    msg_spell_missing = "Inserisci SpellID o nome spell.",
    msg_add_ok = "Aura aggiunta.",
    msg_add_fail = "Errore creazione aura.",
    msg_select_missing = "Nessuna aura selezionata.",
    msg_update_ok = "Aura aggiornata.",
    msg_update_fail = "Errore salvataggio aura.",
    msg_remove_pick = "Seleziona un'aura da rimuovere.",
    msg_remove_ok = "Aura rimossa.",
    msg_duplicate_pick = "Seleziona un'aura da duplicare.",
    msg_duplicate_missing = "Aura selezionata non trovata.",
    msg_duplicate_fail = "Impossibile duplicare aura.",
    msg_duplicate_ok = "Aura duplicata.",
    msg_audio_path_missing = "Percorso audio mancante per %s.",
    msg_language_applied = "Lingua applicata: %s",
    msg_style_applied = "Stile UI applicato: %s",
    rules_title = "Builder Trigger",
    rules_list = "Regole Configurate",
    rules_type = "Tipo Regola",
	    rule_type_if = "Cast -> Mostra Aura",
	    rule_type_consume = "Cast -> Consuma Aura",
	    rule_id = "ID Regola",
	    rule_cast_spell = "SpellID Cast (CSV)",
	    rule_talent_spell = "SpellID Talento (opzionale, CSV)",
    rule_condition_mode = "Logica Condizioni",
    rule_condition_and = "AND (tutte)",
    rule_condition_or = "OR (una qualsiasi)",
	    rule_condition_aura = "SpellID Aura richieste (opzionale, CSV)",
	    rule_condition_combat = "Solo in combat",
	    rule_aura_spell = "SpellID Aura",
		    rule_duration = "Durata (sec)",
		    rule_csv_hint = "Esempio CSV: 6343,23922",
	    rule_narrative_when = "QUANDO Cast",
	    rule_narrative_if = "SE",
	    rule_narrative_then = "ALLORA",
	    rule_narrative_show = "Mostra aura per",
	    rule_narrative_consume = "Consuma aura",
    rules_save = "Salva Regola",
    rules_remove = "Rimuovi Regola",
    rules_clear = "Pulisci Tutte",
    rules_close = "Chiudi",
    rules_new = "Nuova Regola",
    rules_tab_trigger = "Trigger",
    rules_tab_conditions = "Condizioni",
    rules_tab_actions = "Azioni",
    msg_rule_saved = "Regola salvata.",
    msg_rule_removed = "Regole rimosse (%d).",
    msg_rule_clear = "Tutte le regole rimosse.",
    msg_rule_pick = "Seleziona prima una regola.",
    msg_rule_invalid = "Campi regola non validi.",
	    tooltip_aura = "Aura: ",
	    tooltip_source = "Source: ",
	    row_status_ok = "Pronta",
	    row_status_warn = "Da configurare",
	    row_warn_missing_rule = "Nessuna regola trigger configurata (modalita solo regole).",
	    row_warn_missing_texture = "Modalita icona custom selezionata ma path texture vuoto.",
	    row_warn_missing_group = "Il gruppo assegnato e mancante o non valido.",
	  },
}

function L:EnsureOptionsDefaults(options)
  if type(options.language) ~= "string" or not self.tables[options.language] then
    options.language = "enUS"
  end
end

function L:GetLanguage()
  if ns.db and ns.db.options and self.tables[ns.db.options.language] then
    return ns.db.options.language
  end
  return "enUS"
end

function L:SetLanguage(code)
  if not self.tables[code] then
    code = "enUS"
  end
  if ns.db and ns.db.options then
    ns.db.options.language = code
  end
  return code
end

function L:GetLanguageOptions()
  return {
    { value = "enUS", label = self:T("lang_en") },
    { value = "itIT", label = self:T("lang_it") },
  }
end

function L:T(key)
  local code = self:GetLanguage()
  local tableForLang = self.tables[code] or self.tables.enUS
  return tableForLang[key] or self.tables.enUS[key] or key
end
